<?php

/*
*Implements hook_form_alter().
* 
function demo_form_alter(&$form, &$form_state, $form_id) {

	#krumo($form_id);
	switch($form_id) {
		case 'folder_node_form' :
			#krumo($form);
			
			$form['field_folder_status']['und']['#description'] = t('Use this field to indicate the status of work completed in this folder');
			$form['field_folder_image']['#access'] = True;
		krumo($node);
		break;

	}
}
*/
/*
*Implements hook_view().
*
function demo_view($node, $view_mode) {
switch($node)
	if($view_mode == 'full' && node_is_page($node)) {
		$breadcrumb = array();
		$breadcrumb[] = l(t('Home'),NULL);
		$breadcrumb[] = l(t('Example'), 'example');
		$breadcrumb[] = l($node->field1, 'example/' . $node->field1);
		drupal_set_breadcrumb($breadcrumb);
	}
	$node->content['myfield']=array(
		'#markup' => theme('mymodule_myfield', $node->myfield),
		'#weight' => 1,
	);
	return $node;
}
*
*
*Implements hook_form_alter().
*
*
*
*
*/
function demo_form_alter(&$form, &$form_state, $form_id){

	if($form_id == 'transcription_node_form'){
		$form['certify']= array(
			'#type' => 'checkbox',
			'#title' => t('I certify that this is a valid transcription.'),
			'#default_value' => '1',

		);
	

	krumo($form_id);
	}

}
