<?php
//$ID$

/**
 * @file
 * Custom Functions
 */
print curl_download('http://129.15.14.238/mdw/?q=user');
print curl_download('129.15.14.238/mdw/?q=node/2434');

//print curl_download('admin:sasdfs@129.15.14.238/mdw/?q=node/2422');
function curl_download($Url){
 
    // is cURL installed yet?
    if (!function_exists('curl_init')){
        die('Sorry cURL is not installed!');
    }
 
    // OK cool - then let's create a new cURL resource handle
    $ch = curl_init();
 
   // $options = array(CURLOPT_URL => $Url,
//			CURLOPT_HEADER => false, 
//			CURLOPT_AUTOREFERER => 1,
//			CURLOPT_USERAGENT => "MozillaXYZ/1.0",
//			CURLOPT_RETURNTRANSFER => 1,
//			CURLOPT_TIMEOUT => 10,
//			CURLOPT_VERBOSE => 1);
    // Download the given URL, and return output
    curl_setopt($ch, CURLOPT_URL, $Url);
 
    // Set a referer
    curl_setopt($ch, CURLOPT_AUTOREFERER, true);
 
    // User agent
    curl_setopt($ch, CURLOPT_USERAGENT, "Mozilla/4.0 (compatible; MSIE 5.01; Windows NT 5.0)");
 
    // Include header in result? (0 = yes, 1 = no)
    curl_setopt($ch, CURLOPT_HEADER, 0);
 
    // Should cURL return or print out the data? (true = return, false = print)
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
 
    // Timeout in seconds
    curl_setopt($ch, CURLOPT_TIMEOUT, 10);
    curl_setopt($ch, CURLOPT_VERBOSE, true);
    curl_setopt($ch, CURLOPT_USERPWD, 'admin:VT2zDtKMdr!');
    $output = curl_exec($ch);
 
    // Close the cURL resource, and free system resources
    curl_close($ch);
    print("Done");
    return $output;
}
